name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || echo "Testes falharam ou não existem"

      - name: Check code quality
        run: |
          npm install -g eslint
          eslint script.js || echo "Problemas de lint encontrados"

      - name: Build status
        run: |
          echo "Build completed successfully!"
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"

      - name: Prepare deploy folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo rm -rf /var/www/simple-login-temp
            sudo mkdir -p /var/www/simple-login-temp
            sudo chown -R $USER:$USER /var/www/simple-login-temp

      - name: Deploy to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "."
          target: "/var/www/simple-login-temp"
          strip_components: 0
          overwrite: true
          rm: false

      - name: Replace old project and restart app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo rm -rf /var/www/simple-login
